version: '3'
services:
  python-service:
    build: ./app
    container_name: python-metrics-service
    ports:
      - "8000:8000"
    environment:
      - JIRA_EMAIL=value
      - JIRA_API_TOKEN=value
      - QASE_API_TOKEN=value
      - GITHUB_TOKEN=value
      - GITHUB_REPO=value
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - monitoring
    depends_on:
      - prometheus

networks:
  monitoring:
    driver: bridge
