# Docker-compose run command
# docker-compose -p test_pulse up -d --build

version: '3'
services:
  python-metrics-service:
    build: ./app
    container_name: test-puls-python-metrics-service
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - JIRA_EMAIL=value
      - JIRA_API_TOKEN=value
      - QASE_API_TOKEN=value
      - GITHUB_TOKEN=value
      - GITHUB_REPO=value
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:latest
    container_name: test-puls-prometheus
    restart: unless-stopped
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    expose:
      - 9090
    ports:
      - "9090:9090"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: test-puls-grafana
    restart: unless-stopped
    volumes:
      - grafana-data:/var/lib/grafana
    ports:
      - "9020:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - monitoring
    depends_on:
      - prometheus

networks:
  monitoring:
    driver: bridge

volumes:
  prometheus-data:
  grafana-data: