global:
  scrape_interval: 1h

scrape_configs:
  - job_name: 'python-metrics-service'
    scrape_interval: 1h
    static_configs:
      - targets: ['python-metrics-service:8000']
  
  - job_name: 'pushgateway'
    scrape_interval: 1h
    static_configs:
      - targets: ['pushgateway:9091']